[platformio]
src_dir = src

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
src_filter = +<arduino_uno/>
lib_deps = arduino-libraries/Servo

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 9600
upload_speed = 115200
upload_resetmethod = nodemcu
src_filter = +<esp8266_node/>
